<a href="https://colab.research.google.com/github/lucasat2/Jornada_python/blob/main/introducao_pandas/Map.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

data = {
'A': [1,6,np.nan,8,5],
'B':[np.nan,6,3,4,5],
'C': [1,8,3,np.nan,np.nan]
}
df = pd.DataFrame(data)
df

# df com notas de alunos
# 3 disciplinas (A,B,C), a média é 6
# nulo nao fez, 4 reprovado e 5 recuperaçao

     A    B    C
0  1.0  NaN  1.0
1  6.0  6.0  8.0
2  NaN  3.0  3.0
3  8.0  4.0  NaN
4  5.0  5.0  NaN

In [5]:
def calculaNotas(nota):

	if pd.isna(nota):
		return 'Nao fez a prova'
	elif nota <= 4:
		return 'Reprovado'
	elif nota < 6 and nota >= 5:
		return 'Recuperação'
	else:
		return 'Aprovado'

df_com_notas = df.map(calculaNotas)
df_com_notas

                 A                B                C
0        Reprovado  Nao fez a prova        Reprovado
1         Aprovado         Aprovado         Aprovado
2  Nao fez a prova        Reprovado        Reprovado
3         Aprovado        Reprovado  Nao fez a prova
4      Recuperação      Recuperação  Nao fez a prova