<a href="https://colab.research.google.com/github/lucasat2/Jornada_python/blob/main/Projeto_Analise_voo/Projeto_Pandas_Analise_dados_voo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('flights.csv')

In [5]:
df.head(10)

,Origin,Destination,Origin City,Destination City,Passengers,Seats,Flights,Distance,Fly Date,Origin Population,Destination Population
0,MHK,AMW,"Manhattan, KS","Ames, IA",21,30,1,254.0,200810,122049,86219
1,EUG,RDM,"Eugene, OR","Bend, OR",41,396,22,103.0,199011,284093,76034
2,EUG,RDM,"Eugene, OR","Bend, OR",88,342,19,103.0,199012,284093,76034
3,EUG,RDM,"Eugene, OR","Bend, OR",11,72,4,103.0,199010,284093,76034
4,MFR,RDM,"Medford, OR","Bend, OR",0,18,1,156.0,199002,147300,76034
5,MFR,RDM,"Medford, OR","Bend, OR",11,18,1,156.0,199003,147300,76034
6,MFR,RDM,"Medford, OR","Bend, OR",2,72,4,156.0,199001,147300,76034
7,MFR,RDM,"Medford, OR","Bend, OR",7,18,1,156.0,199009,147300,76034
8,MFR,RDM,"Medford, OR","Bend, OR",7,36,2,156.0,199011,147300,76034
9,SEA,RDM,"Seattle, WA","Bend, OR",8,18,1,228.0,199002,5154164,76034

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3606803 entries, 0 to 3606802
Data columns (total 11 columns):
 #   Column                  Dtype
---  ------                  -----
 0   Origin                  object
 1   Destination             object
 2   Origin City             object
 3   Destination City        object
 4   Passengers              int64
 5   Seats                   int64
 6   Flights                 int64
 7   Distance                float64
 8   Fly Date                int64
 9   Origin Population       int64
 10  Destination Population  int64
dtypes: float64(1), int64(6), object(4)
memory usage: 302.7+ MB

In [7]:
df.isnull().sum()

Origin                    0
Destination               0
Origin City               0
Destination City          0
Passengers                0
Seats                     0
Flights                   0
Distance                  0
Fly Date                  0
Origin Population         0
Destination Population    0
dtype: int64

In [9]:
df.describe().round(2)

,Passengers,Seats,Flights,Distance,Fly Date,Origin Population,Destination Population
count,3606803.00,3606803.00,3606803.00,3606803.00,3606803.00,3606803.0,3606803.00
mean,2688.91,4048.30,37.23,697.32,200063.39,5871502.5,5897982.44
std,4347.62,6200.87,49.62,604.42,574.67,7858061.6,7906127.41
min,0.00,0.00,0.00,0.00,199001.00,13005.0,12887.00
25%,109.00,156.00,2.00,273.00,199603.00,1030597.0,1025470.00
50%,1118.00,1998.00,25.00,519.00,200111.00,2400193.0,2400193.00
75%,3503.00,5370.00,55.00,927.00,200601.00,8613622.0,8635706.00
max,89597.00,147062.00,1128.00,5095.00,200912.00,38139592.0,38139592.00

In [10]:
# pegando dados categoricos

df['Origin'].value_counts().head(10)

Origin
ORD    158496
ATL    131046
DFW    106698
DTW     99624
MSP     98922
LAX     87299
CLT     85615
PHL     83244
IAH     81249
EWR     79810
Name: count, dtype: int64

In [11]:
# dados categoricos unicos
# Todos os aeroportos de origem

df['Origin'].unique()

array(['MHK', 'EUG', 'MFR', 'SEA', 'PDX', 'LMT', 'SFO', 'LAX', 'EAT',
       'YKM', 'EKO', 'SLE', 'GEG', 'RDD', 'LWS', 'AST', 'CLM', 'PDT',
       'SJC', 'ACV', 'PUW', 'SMF', 'FLL', 'PHX', 'BFI', 'GGG', 'GTF',
       'FAT', 'TUS', 'MWH', 'BIL', 'DFW', 'RBG', 'SLC', 'CPR', 'RDM',
       'RNO', 'FBK', 'ANC', 'BIF', 'CIC', 'SAF', 'ABQ', 'FSM', 'LAS',
       'DQF', 'ICT', 'AZA', 'DLH', 'CEC', 'OKC', 'SAN', 'STS', 'DRO',
       'OAK', 'IAH', 'ELP', 'DBQ', 'HLN', 'TUL', 'OMA', 'ACT', 'BTM',
       'AUS', 'PIA', 'CWA', 'PUB', 'FOE', 'COS', 'GJT', 'LBF', 'SPS',
       'CYS', 'ABR', 'BRD', 'AMA', 'ROW', 'BIS', 'MSO', 'GCC', 'LBB',
       'LBL', 'MAF', 'MSN', 'LNK', 'ALO', 'RFD', 'GRB', 'LSE', 'FCA',
       'MKE', 'BLI', 'FOD', 'DSM', 'EAU', 'MCW', 'RAP', 'LIT', 'SHV',
       'MCI', 'GFK', 'BFL', 'SAT', 'MSP', 'SGF', 'BFF', 'FSD', 'GRI',
       'CID', 'FYV', 'SUX', 'GCK', 'BTR', 'IDA', 'SPI', 'SBA', 'CRP',
       'DEC', 'ORD', 'BZN', 'PIR', 'MLU', 'YUM', 'MOT', 'GYY', 'FAR',
       'RST', 'STL', 'BNA', 'EVV', 'MEM', 'JAN', 'MOD', 'CMI', 'SCK',
       'IND', 'BMI', 'TWF', 'LRD', 'CAK', 'MTJ', 'CLE', 'CLL', 'DTW',
       'ABI', 'DAY', 'CVG', 'JAC', 'CMH', 'SBN', 'FWA', 'AZO', 'HOU',
       'RKS', 'BPT', 'PIH', 'SLN', 'UIN', 'LAW', 'TOL', 'RIW', 'BRO',
       'SJT', 'PRB', 'SHR', 'MCE', 'GRK', 'VGT', 'CDC', 'PNC', 'HRO',
       'WDG', 'RCA', 'BWD', 'DDC', 'PIT', 'ORH', 'ITH', 'ELM', 'BOS',
       'ATL', 'MDW', 'PHL', 'GSO', 'FNT', 'BUF', 'EWR', 'BGR', 'CLT',
       'JFK', 'SYR', 'RIC', 'GRR', 'YIP', 'ABE', 'LGA', 'PVD', 'LEX',
       'BHM', 'ACY', 'MCO', 'YNG', 'PWM', 'MDT', 'BGM', 'IAD', 'ALB',
       'MSY', 'ROC', 'AVP', 'ROA', 'RDU', 'GSP', 'BTV', 'CRW', 'CHS',
       'DCA', 'CHA', 'SCE', 'CHO', 'LAN', 'BDL', 'CAE', 'JHW', 'MHT',
       'ILM', 'GDC', 'FLO', 'ISO', 'BWI', 'ERI', 'SFB', 'PGV', 'TYS',
       'HSV', 'BWG', 'ADS', 'DET', 'LOZ', 'SUS', 'WGO', 'GSB', 'MYR',
       'MBS', 'CLU', 'LCK', 'SYI', 'TLH', 'BMG', 'MNN', 'LUK', 'MGM',
       'MFD', 'PNS', 'ASN', 'TVC', 'KY5', 'MIA', 'GPT', 'TCL', 'DRT',
       'AEX', 'HUF', 'RWI', 'TPA', 'SNA', 'AGC', 'GBD', 'FAI', 'EAR',
       'BRL', 'JLN', 'TBN', 'HNL', 'OGG', 'NFL', 'DAL', 'MHR', 'LFT',
       'SCF', 'HIK', 'KTN', 'LCH', 'ILN', 'MOB', 'FWH', 'LGU', 'XNA',
       'LRU', 'RIV', 'COU', 'ILE', 'ESF', 'TYR', 'JAX', 'PBI', 'SAV',
       'FLG', 'EFD', 'AFW', 'CNW', 'SWO', 'SKF', 'CSG', 'ELD', 'FFO',
       'PAM', 'GNV', 'HMN', 'ILG', 'DMA', 'FTW', 'HII', 'IPL', 'POB',
       'TCM', 'SBP', 'TTN', 'ATW', 'BTL', 'PDK', 'LAF', 'RDG', 'MKG',
       'HGR', 'MQT', 'NZC', 'UCA', 'FAY', 'AGS', 'AVL', 'VLD', 'EKA',
       'DOV', 'NKX', 'LUF', 'CVS', 'BAD', 'LSV', 'TIK', 'EIL', 'JMS',
       'MWA', 'GLH', 'EKI', 'VWL', 'SZL', 'LAR', 'OSH', 'MOR', 'PWK',
       'APN', 'IRK', 'PAH', 'MRC', 'CSV', 'GMU', 'DPA', 'DCU', 'SKY',
       'ADM', 'CNM', 'CVN', 'HOB', 'FMN', 'RUI', 'BKX', 'HON', 'BQK',
       'ABY', 'DHN', 'OAJ', 'MEI', 'GTR', 'PFN', 'LYH', 'MCN', 'EYW',
       'BKL', 'ARA', 'APF', 'EWN', 'AHN', 'EDF', 'DYS', 'BYH', 'MCF',
       'MIQ', 'NQX', 'LTS', 'TNT', 'OPF', 'HKY', 'CKB', 'NPA', 'WRB',
       'TUP', 'PIB', 'NJK', 'LSF', 'OCF', 'MIE', 'NEW', 'SVN', 'ORL',
       'NIP', 'FXE', 'NBG', 'SDM', 'MXF', 'SSC', 'JST', 'HKS', 'AND',
       'BFM', 'TMB', 'HIF', 'HOT', 'PNE', 'MTN', 'LAL', 'MKC', 'SHD',
       'XXW', 'MIO', 'MIB', 'ISN', 'DIK', 'BMC', 'SGU', 'MUO', 'OGD',
       'SAW', 'OFK', 'NZY', 'CVO', 'ITO', 'MDH', 'AID', 'SGH', 'OLS',
       'ANB', 'FDY', 'BDR', 'HVN', 'RUT', 'OGS', 'RKD', 'ART', 'STC',
       'AUO', 'PBG', 'IMT', 'PVU', 'CGI', 'PKB', 'THV', 'AUG', 'SBY',
       'CUB', 'PGD', 'FVS', 'SVC', 'CRS', 'IPT', 'JBR', 'SQI', 'EGP',
       'ATY', 'GAD', 'VCT', 'RMG', 'MCC', 'STJ', 'BKG', 'BJI', 'CHI',
       'MKL', 'MVN', 'HLM', 'MGY', 'LEW', 'BFD', 'GUP', 'UKI', 'OXR',
       'VIS', 'SOW', 'HVR', 'HYS', 'WFB', 'JNU', 'JSE', 'ADQ', 'KDK',
       'AOO', 'MS1', 'NQA', 'HUM', 'MML', 'MMI', 'IRS', 'JEF', 'MPB',
       'SRC', 'GLW', 'SPA', 'TN6', 'CEV', 'SER', 'BGD', 'AIY', 'JRA',
       'JRB', 'TSS', 'LNS', 'SUM', 'ALW', 'SAC', 'OKK', 'POU', 'VAD',
       'LKE', 'SKA', 'BSM', 'GRF', 'DLF', 'APC', 'ESC', 'CWI', 'BGS',
       'SWW', 'BFR', 'ZZV', 'ISM', 'WQM', 'AXN', 'FFM', 'GWO', 'FEP',
       'KY1', 'GVL', 'AOH', 'STP', 'BKW', 'DNN', 'CPS', 'PSF', 'DUC',
       'UVA', 'MOP', 'BJJ', 'JXN', 'OWB', 'SIK', 'AXV', 'DMO', 'FFT',
       'II2', 'DNV', 'SAD', 'FTY', 'UCY', 'PHT', 'IN1', 'TDZ', 'NC3',
       'EKX', 'TN3', 'PBF', 'BVX', 'THA', 'OH5', 'SBM', 'KY3', 'OH3',
       'ATO', 'VWT', 'WV1', 'DVN', 'CGF', 'OH2', 'SRW', 'YKN', 'OTM',
       'GCY', 'GUS', 'MMT', 'LUL', 'OFF', 'ALM', 'PUC', 'LFK', 'BBC',
       'VWH', 'SEM', 'RID', 'SVH', 'MI2', 'VEL', 'MKT', 'ASL', 'HFD',
       'PRC', 'DVT', 'AR1', 'IAB', 'ODW', 'OLM', 'END', 'MVW', 'GBG',
       'PWT', 'SHN', 'ELN', 'LGD', 'SFF', 'VWD', 'MAE', 'HUT', 'SSI',
       'UBS', 'CBM', 'GFL', 'NY3', '1B1', 'FCH', 'WTC', 'PWA', 'TIW',
       'PMH', 'CAD', 'MGW', 'TBR', 'CBE', 'MDD', 'MRI', 'LSD', 'HCA',
       'SLB', 'DQU', 'OSU', 'MYF', 'SEE', 'AMW', 'LWC', 'MZZ', 'OWA',
       'DNE', 'HSH', 'LWF', 'HBG', 'GRD', 'JZU', 'AMK', 'RND', 'IKK',
       'FET', 'TMA', 'ECG', 'STF', 'LAM', 'TSM', 'TX6', 'OH1', 'S27',
       'DQC', 'MHL', 'MHE', 'TKF', 'CGX', 'WMH', 'LXN', 'HSI', 'WBR',
       'GGE', 'HLG', 'LHV', 'CRE', 'BOK', 'BIH', 'MQJ', 'LCI'],
      dtype=object)

In [12]:
# Contando quantos aeroportos
df['Origin'].nunique()

683

In [14]:
# Filtrando os dados para coisas menores

#Cenario 1 : Extrair registros de voos apenas no ano 2000

df['Year'] =df['Fly Date'].astype(str).str.slice(0,4) #extraindo os 4 primeiros digitos do ano e transformando em string.
voos2000 = df[df['Year'] == '2000']

In [15]:
voos2000

,Origin,Destination,Origin City,Destination City,Passengers,Seats,Flights,Distance,Fly Date,Origin Population,Destination Population,Year
636,SEA,RDM,"Seattle, WA","Bend, OR",2023,4144,112,228.0,200001,6104758,116618,2000
637,SEA,RDM,"Seattle, WA","Bend, OR",2995,4699,127,228.0,200012,6104758,116618,2000
638,SEA,RDM,"Seattle, WA","Bend, OR",3134,5328,144,228.0,200009,6104758,116618,2000
639,SEA,RDM,"Seattle, WA","Bend, OR",3420,5328,144,228.0,200006,6104758,116618,2000
640,SEA,RDM,"Seattle, WA","Bend, OR",3108,5106,138,228.0,200010,6104758,116618,2000
...,...,...,...,...,...,...,...,...,...,...,...,...
3606696,STL,TBN,"St. Louis, MO","Fort Leonard Wood, MO",663,1425,75,119.0,200003,2701634,41712,2000
3606697,STL,TBN,"St. Louis, MO","Fort Leonard Wood, MO",166,342,18,119.0,200005,2701634,41712,2000
3606698,STL,TBN,"St. Louis, MO","Fort Leonard Wood, MO",548,1254,66,119.0,200001,2701634,41712,2000
3606699,STL,TBN,"St. Louis, MO","Fort Leonard Wood, MO",456,1311,69,119.0,200002,2701634,41712,2000
3606700,STL,TBN,"St. Louis, MO","Fort Leonard Wood, MO",589,1330,70,119.0,200004,2701634,41712,2000

In [16]:
#Cenario 2 : Encontre voos que nao incluam LAX como origem

voos_sem_lax = df[df['Origin'] != 'LAX']

In [17]:
voos_sem_lax

,Origin,Destination,Origin City,Destination City,Passengers,Seats,Flights,Distance,Fly Date,Origin Population,Destination Population,Year
0,MHK,AMW,"Manhattan, KS","Ames, IA",21,30,1,254.0,200810,122049,86219,2008
1,EUG,RDM,"Eugene, OR","Bend, OR",41,396,22,103.0,199011,284093,76034,1990
2,EUG,RDM,"Eugene, OR","Bend, OR",88,342,19,103.0,199012,284093,76034,1990
3,EUG,RDM,"Eugene, OR","Bend, OR",11,72,4,103.0,199010,284093,76034,1990
4,MFR,RDM,"Medford, OR","Bend, OR",0,18,1,156.0,199002,147300,76034,1990
...,...,...,...,...,...,...,...,...,...,...,...,...
3606798,STL,TBN,"St. Louis, MO","Fort Leonard Wood, MO",281,969,51,119.0,200902,2828990,46457,2009
3606799,STL,TBN,"St. Louis, MO","Fort Leonard Wood, MO",245,1026,54,119.0,200911,2828990,46457,2009
3606800,STL,TBN,"St. Louis, MO","Fort Leonard Wood, MO",363,1273,67,119.0,200908,2828990,46457,2009
3606801,CGI,TBN,"Cape Girardeau, MO","Fort Leonard Wood, MO",2,19,1,146.0,200908,93712,46457,2009
3606802,FWA,OH1,"Fort Wayne, IN","Washington Court House, OH",0,0,1,135.0,200309,398574,28133,2003

In [19]:
# Cenario 3 : Voos que incluam LAX


voos_lax = df[df['Origin'] =='LAX']

voos_lax

,Origin,Destination,Origin City,Destination City,Passengers,Seats,Flights,Distance,Fly Date,Origin Population,Destination Population,Year
73,LAX,RDM,"Los Angeles, CA","Bend, OR",1599,2992,22,726.0,199003,22585772,76034,1990
74,LAX,RDM,"Los Angeles, CA","Bend, OR",643,2856,21,726.0,199001,22585772,76034,1990
75,LAX,RDM,"Los Angeles, CA","Bend, OR",1280,2720,20,726.0,199002,22585772,76034,1990
76,LAX,RDM,"Los Angeles, CA","Bend, OR",66,104,1,726.0,199001,22585772,76034,1990
1112,LAX,RDM,"Los Angeles, CA","Bend, OR",154,210,3,726.0,200612,25427320,148670,2006
...,...,...,...,...,...,...,...,...,...,...,...,...
3606280,LAX,HII,"Los Angeles, CA","Lake Havasu City, AZ",186,418,22,236.0,199611,23326070,125838,1996
3606281,LAX,HII,"Los Angeles, CA","Lake Havasu City, AZ",991,1501,79,236.0,199605,23326070,125838,1996
3606282,LAX,HII,"Los Angeles, CA","Lake Havasu City, AZ",822,1425,75,236.0,199607,23326070,125838,1996
3606283,LAX,HII,"Los Angeles, CA","Lake Havasu City, AZ",745,1387,73,236.0,199610,23326070,125838,1996
3606284,LAX,HII,"Los Angeles, CA","Lake Havasu City, AZ",851,1406,74,236.0,199606,23326070,125838,1996