In [18]:
usuarios = [
    {
        "id": 1,
        "nome": "Ana",
        "endereco": {
            "cidade": "Juiz de Fora",
            "estado": "MG"
        },
        "planos": ["básico", "data-science"]
    },
    {
        "id": 2,
        "nome": "Bruno",
        "endereco": {
            "cidade": "São Paulo",
            "estado": "SP"
        },
        "planos": ["premium"]
    },
    {
        "id": 3,
        "nome": "Carla",
        "endereco": {
            "cidade": "Rio de Janeiro",
            "estado": "RJ"
        },
        "planos": ["básico"]
    }
]

# Use json_normalize para transformar usuarios em um DataFrame.

In [19]:
from pandas import json_normalize

df = json_normalize(usuarios)

# Verifique quais colunas foram criadas.

In [20]:
print(df.columns)

Index(['id', 'nome', 'planos', 'endereco.cidade', 'endereco.estado'], dtype='object')

# Crie um DataFrame df_simplificado com as colunas:

In [21]:
df_simplificado = df.rename(columns= {

    'endereco.cidade' : 'cidade',
    'endereco.estado' : 'estado',
})

In [22]:
print(df_simplificado.columns)

Index(['id', 'nome', 'planos', 'cidade', 'estado'], dtype='object')

# (Desafio extra) Filtre apenas os usuários que têm o plano "data-science" na lista planos.
Dica: você pode usar df["planos"].str.contains("data-science") depois de criar a coluna, ou tratar essa parte separados antes de virar DataFrame.

In [23]:
df_simplificado

   id   nome                  planos          cidade estado
0   1    Ana  [básico, data-science]    Juiz de Fora     MG
1   2  Bruno               [premium]       São Paulo     SP
2   3  Carla                [básico]  Rio de Janeiro     RJ

In [24]:
df_filtrado = df_simplificado[df_simplificado['planos'].apply(lambda x: 'data-science' in x)]

df_filtrado

   id nome                  planos        cidade estado
0   1  Ana  [básico, data-science]  Juiz de Fora     MG